format = """
[î‚¶](green)\
$os\
$username\
[î‚°](green bg:yellow)\
$directory\
[î‚°](fg:yellow bg:red)\
$git_branch\
$git_status\
[î‚°](fg:red bg:blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:blue bg:cyan)\
$docker_context\
[î‚°](fg:cyan bg:purple)\
$time\
[î‚° ](fg:purple)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:green fg:black bold"
style_root = "bg:red fg:white bold"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:green fg:black"
disabled = false # Disabled by default

[directory]
style = "bg:yellow fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:cyan fg:black"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:red fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:red fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:blue fg:black bold"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:purple fg:black bold"
format = '[ â™¥ $time ]($style)'
